#1 Creating a dictionary of my favorite things
print("Ex 1")
favorite={'livro':'Foco- Daniel Goleman, Sherlock Holms- Conan Doyle','arvores':'Flamboyland, mangueira, manaca, paineira','jogos':'truco, ping-pong, futebol, ciclismo'}

#2 print do livro favorito:
print("Ex 2")
print("Livros Favoritos:", favorite['livro'])

#3 Print os livros favoritos usando uma variável
print("Ex3")
Fav_livros=favorite['livro']
print("Livros Favoritos usando uma variável:", Fav_livros)

#4 Print favorite tree:
print("Ex 4")
print("Árvors Favoritas: ", favorite['arvores'])

#5 Adicionando o organismo favorito no dicionário
print("Ex 5")
favorite['organismo']='papagaio'
print("Novo dicionário: ", favorite)
fav_thing=favorite['organismo']
print("Organismo favorito:", fav_thing)

#6 inserir valor para fav_thing da linha de comandos atraves do "input"
print("Ex 6")
K=input("Escolha uma Key - 'fav_thing, livro, arvores, jogos':")
print(K)
objeto=input("Escolha um novo valor para Key - fav_thing:")
favorite['fav_thing']=objeto
print("Dicionário atualizado", favorite)

#7 mudando o organismo favorito:
print("Ex 7")
favorite['fav_thing']='peixe'


#8 escolha o valor do organismo favorito e use a função input para muda-lo:
print("Ex 8")
print(favorite['fav_thing'])
favorite['organismo']=input("escolha um novo organismo favorito:")
print("Dicionário atualizado", favorite)

#9 use um loop para imprimir valores de cada key e seu correspondente no dicionário
print("Ex 9")
for key in favorite:
 print(key, ':', favorite[key])
 
#10 Crie duas variáveis uma utilizando formato list e outra dictionary:
print("Ex 10")
myset= set('ATTGGCT')
myset2={'ATTGGCT'}

print('resposta ex 10: A lista é um formato que pode conter integers, strings ou objetos na mesma lista, sendo ela mutável, seus elementos são acessados por indices numericos e a ordem sempre será mantida nos elementos.No exercício acima o dicionário myset2 não adicionou uma key para o elemento assim ele não está corretamento inserio no formato dict.')
print("myset:", myset, "myset2:", myset2) 

#11 Encontrar a união, intersecção e simetria nos sets:
print("Ex 11:")
#print("união:", a | b)
#Set A = 3 14 15 9 26 5 35 9
#Set B = 60 22 14 0 9
a=set('3,14,15,9,26,5,35,9')
b=set('60,22,14,0,9')
print("união:",a|b)
print("intersecção:",a&b)
print("difetença:",a^b)

#12 Criar um set usando uma sequência de DNA:
print("Ex 12")
c=set('GATGGGATTGGGGTTTTCCCCTCCCATGTGCTCAAGACTGGCGCTAAAAGTTTTGAGCTTCTCAAAAGTCTAGAGCCACCGTCCAGGGAGCAGGTAGCTGCTGGGCTCCGGGGACACTTTGCGTTCGGGCTGGGAGCGTGCTTTCCACGACGGTGACACGCTTCCCTGGATTGGCAGCCAGACTGCCTTCCGGGTCACTGCCATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGCCCCCTCTGAGTCAGGAAACATTTTCAGACCTATGGAAACTACTTCCTGAAAACAACGTTCTGTCCCCCTTGCCGTCCCAAGCAATGGATGATTTGATGCTGTCCCCGGACGATATTGAACAATGGTTCACTGAAGACCCAGGTCCAGATGAAGCTCCCAGAATTCGCCAGAGGCTGCTCCCCCCGTGGCCCCTGCACCAGCAGCTCCTACACCGGCGGCCCCTGCACCAGCCCCCTCCTGGCCCCTGTCATCTTCTGTCCCTTCCCAGAAAACCTACCAGGGCAGCTACGGTTTCCGTCTGGGCTTCTTGCATTCTGGGACAGCCAAGTCTGTGACTTGCACGTACTCCCCTGCCCTCAACAAGATGTTTTGCCAACTGGCCAAGACCTGCCCTGTGCAGCTGTGGGTTGATTCCACACCCCCGCCCGGCACCCGCGTCCGCGCCATGGCCATCTACAAGCAGTCACAGCACATGACGGAGGTTGTGAGGCGCTGCCCCCACCATGAGCGCTGCTCAGATAGCGATGGTCTGGCCCCTCCTCAGCATCTTATCCGAGTGGAAGGAAATTTGCGTGTGGAGTATTTGGATGACAGAAACACTTTTCGTGGGGTTTTCCCCTCCCATGTGCTCAAGACTGGCGCTAAAAGTTTTGAGCTTCTCAAAAGTCTAGAGCCACCGTCCAGGGAGCAGGTAGCTGCTGGGCTCCGGGGACACTTTGCGTTCGGGCTGGGAGCGTGCTTTCCACGACGGTGACACGCTTCCCTGGATTGGCAGCCAGACTGCCTTCCGGGTCACTGCCATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGCCCCCTCTGAGTCAGGAAACATTTTCAGACCTATGGAAACTACTTCCTGAAAACAACGTTCTGTCCCCCTTGCCGTCCCAAGCAATGGATGATTTGATGCTGTCCCCGGACGATATTGAACAATGGTTCACTGAAGACCCAGGTCCAGATGAAGCTCCCAGAATTCGCCAGAGGCTGCTCCCCCCGTGGCCCCTGCACCAGCAGCTCCTACACCGGCGGCCCCTGCACCAGCCCCCTCCTGGCCCCTGTCATCTTCTGTCCCTTCCCAGAAAACCTACCAGGGCAGCTACGGTTTCCGTCTGGGCTTCTTGCATTCTGGGACAGCCAAGTCTGTGACTTGCACGTACTCCCCTGCCCTCAACAAGATGTTTTGCCAACTGGCCAAGACCTGCCCTGTGCAGCTGTGGGTTGATTCCACACCCCCGCCCGGCACCCGCGTCCGCGCCATGGCCATCTACAAGCAGTCACAGCACATGACGGAGGTTGTGAGGCGCTGCCCCCACCATGAGCGCTGCTCAGATAGCGATGGTCTGGCCCCTCCTCAGCATCTTATCCGAGTGGAAGGAAATTTGCGTGTGGAGTATTTGGATGAC')
print(c)
print("apenas será obtido cada tipo de caracter utilizado")

#13 Determinar o caractere exclusivo da sequencia:
dna='GAACTCCAAAAATGAAAACATAGTAGCAATCAAAGCATCCCACTATTTTTTGTCTCTCGTTTCATTAGCGTTGTAAATTACTGATACCCTACTATACCTCTACAAGGCCTTTGTCATCTTTTTACTCAAGTGTGAAATCATCACTTATTGTATGAAGGATGAGCTTTCCGTTCGCTAGTTTGCTGAAAAGGCCTTCTGCAATAAGCTCTCTATTATCTTTAAAAAAACCTGGTTCCTGGTCTTCCATTCTGCTAAAAGCTGTAGGGGTTTTATCACGAGATTCCCGTTGGCATTCTGACTTATTAAAAATGCTTACAGAAGAAATGGATTCTTTAAATGGTCAAATTAATACGTGGACAGATAATAATCCTTTATTAGATGAAATTACGAAGCCATACAGAAAATCTTCAACTCGTTTTTTTCATCCGCTTCTTGTACTTCTAATGTCTAGAGCATCAGTAAATGGGGATCCACCGAGTCAGCAACTATTTCAAAGGTACAAACAACTTGCCCGTGTAACAGAATTGATTCATGCTGCCAATATAATTCATATTAATATTGGAGAAGAACAAAGCAACGAACAGATTAAACTTGCAACGTTGGTTGGAGATTATTTACTCGGAAAGGCGTCTGTTGATTTAGCACATTTAGAAAACAACGCTATTACAGAAATTATGGCTTCTGTTATTGCAAACTTAGTTGAAGGGCACTTCGGAAGCCGACAAAATGGCTCTGTTGGTTTGTCAAACGAACGAACCATCCTTCTGCAATCAGCCTTTATGCCAGCAAAGGCATGTTTATGCGCAAGCATATTGAATAACTCATCACAATACATTAATGATGCGTGTTTCAATTATGGAAAATTTCTAGGCTTATCGCTGCAACTGGCCCATAAGCCTGTATCTCCTGACGCCCAAGTTTTGCAAAAGAATAATGACATTTTGAAAACATATGTTGAGAATGCCAAGAGCTCATTGTCTGTTTTCCCCGATATAGAGGCTAAGCAAGCTCTCATGGAAATCGCTAATAGTGTTTCGAAGTAATCGACAGGTATTGTATCCTGGATTAATATTAGGGTGGCTCATGCATGCTCGTGCAATCGTAACAAATATGTCTTTCTTTTACGAATTTTAACGCTTCAATATAAATCATATTTTTCCTCA'
nt_count={}
unique=set(dna)
print('unique nt: ', unique)
for nt in unique:
 count= dna.count(nt)
 nt_count[nt]=count
print('nt count:',nt_count)
DNA={'A':'','T':'','G':'','C':'','GC':''}
DNA['A']=nt_count['A']
DNA['G']=nt_count['G']
DNA['T']=nt_count['T']
DNA['C']=nt_count['C']
print("Contano o numero de cada nucleotideo e armazenando na Dict DNA:",DNA)
